// Foloe 产品数据索引（用于顶部搜索）
var FOLOE_PRODUCTS = [
    { name: "PogoPin探针卡植针机", cat: "智能化高精度加工检测设备", url: "products/pogopin-probe-insertion-machine.html",
      summary: "兼容直径0.2–2mm，装配公差≤0.01mm，组装速度1,500 pcs/hr。",
      kw: "植针机 探针卡 pogopin 半导体测试探针 组装 插针" },
    { name: "PogoPin探针组装与植针一体机", cat: "智能化高精度加工检测设备", url: "products/pogopin-probe-assembly-insertion-machine.html",
      summary: "自动打点、插接、铆合、植针一体化，探针制造全流程自动化。",
      kw: "组装机 植针一体机 pogopin 打点 铆合 插接 探针" },
    { name: "半自动PogoPin探针打点组装机", cat: "智能化高精度加工检测设备", url: "products/semi-automatic-pogopin-dispensing-assembly-machine.html",
      summary: "手动辅助探针打点与组装，支持完全离线独立运行，适配小批量试制。",
      kw: "半自动 打点 组装机 pogopin 探针 离线" },
    { name: "全自动PogoPin探针打点组装机", cat: "智能化高精度加工检测设备", url: "products/automatic-pogopin-dispensing-assembly-machine.html",
      summary: "在搭载半自动探针组装机的基础上实现全自动探针组装，上位机调节。",
      kw: "全自动 打点 组装机 pogopin 探针 上位机" },
    { name: "探针综合检料仪", cat: "智能化高精度加工检测设备", url: "products/probe-inspection-sorter.html",
      summary: "机器视觉自动识别，探针计数 + 外形质量检测，服务来料检验与质量控制。",
      kw: "检料仪 检料 计数 外观 质量检测 机器视觉 探针" },
    { name: "芯片封装热压贴头焊机模块", cat: "智能化高精度加工检测设备", url: "products/thermal-compression-bonding-module.html",
      summary: "芯片吸附、角度控制与水平调节，精确升降温，支持银浆固化工艺。",
      kw: "芯片封装 热压 贴头 焊机 贴片机 银浆 封装" },
    { name: "全自动探针针压测试仪", cat: "智能化高精度加工检测设备", url: "products/probe-force-tester.html",
      summary: "Excel坐标输入 + 视觉图像识别，全自动针压测量，三维图形输出。",
      kw: "针压 测试仪 针压测试 探针卡 弹力 测力 晶圆测试" },
    { name: "步进电机多路驱控一体卡", cat: "专用控制板卡与工业控制软件", url: "products/multi-axis-motion-controller.html",
      summary: "较传统控制器缩小体积，实现多路控制、多种控制方式、精准调节。",
      kw: "驱控一体卡 步进电机 控制卡 光源控制卡 wifi 运动控制" },
    { name: "多通道AD/DA采集卡", cat: "专用控制板卡与工业控制软件", url: "products/multi-channel-ad-da-card.html",
      summary: "单板100通道 AD/DA，12位精度，支持多板并联扩展，弹簧探针接触。",
      kw: "AD DA 采集卡 多通道 数据采集 adda 板卡" },
    { name: "IC与功率器件高温老化测控卡", cat: "专用控制板卡与工业控制软件", url: "products/htol-test-card.html",
      summary: "40组独立控制通道，25–175°C双向PID控温，多设备联网监控。",
      kw: "老化 测控卡 htol 高温老化 ic mosfet igbt 功率器件" },
    { name: "燃料棒内氦压无损检测设备控制软件", cat: "专用控制板卡与工业控制软件", url: "products/helium-pressure-control-software.html",
      summary: "实时采集双通道温度数据，配合PLC实现自动化控制，一键启动11步检测流程。",
      kw: "氦压 无损检测 控制软件 燃料棒 plc 气压检测" },
    { name: "磁悬浮转子三维刚度测试仪", cat: "科学仪器与设备", url: "products/magnetic-levitation-stiffness-tester.html",
      summary: "定位精度0.01mm，三维力测量±50N，服务人工心脏与磁悬浮轴承测试。",
      kw: "磁悬浮 刚度测试 转子 人工心脏 血泵 磁悬浮轴承 三维力" },
    { name: "微纳三维金属加工设备", cat: "科学仪器与设备", url: "products/micro-nano-3d-metal-printer.html",
      summary: "微米/亚微米级 3D增材制造，室温大气环境直接成型，精确定位、原位加工。",
      kw: "微纳 三维打印 金属加工 增材制造 3d打印 探针卡 脑机接口" },
    { name: "智能多芯线缆测试仪", cat: "科学仪器与设备", url: "products/smart-multi-core-cable-tester.html",
      summary: "100芯线束快速自动检测，内置100V绝缘耐压测试，图形化显示与自动报告。",
      kw: "线缆测试 多芯 线束 耐压测试 绝缘 电阻测量" }
];
